modLoader="javafml" 
loaderVersion="[29,)"
issueTrackerURL="https://github.com/AzureZhen/Azure-RPG-Items/issues" 
[[mods]]
modId="azurerpgitems"
version="${file.jarVersion}"
displayName="Azure RPG Items"
displayURL="https://www.curseforge.com/minecraft/mc-mods/azure-rpg-items"
logoFile="azurerpglogo.png"
authors="AzureDoomC" 
description='''
This is a small RPG mod with built in support with Mine and Slash and Curios.
'''