modLoader="javafml" 
loaderVersion="[28,)"
issueTrackerURL="http://my.issue.tracker/" 
[[mods]]
modId="azurerpgitems"
version="${file.jarVersion}"
displayName="Azure RPG Items"
displayURL="http://example.com/"
logoFile="azurerpglogo.png"
authors="AzureDoomC" 
description='''
This is a small RPG mod with built in support with Mine and Slash and Curios.
'''
[[dependencies.azurerpgitems]]
    modId="curios" 
    mandatory=true 
    versionRange="[FORGE-1.14.4-1.0,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.azurerpgitems]]
    modId="mmorpg" 
    mandatory=true 
    versionRange="[1.14.4-2.9.3,)" 
    ordering="NONE"
    side="BOTH"